export const BUILT_IN_MODEL_CATALOG = [
  {
    id: "Qwen/Qwen2.5-0.5B-Instruct-GGUF",
    name: "Qwen2.5 0.5B Instruct",
    provider: "builtin",
    params: "0.5B",
    quantization: "Q4_K_M",
    sizeGb: 0.4,
    minimumRamGb: 4,
    recommendedRamGb: 8,
    runtimeTags: ["gguf", "llama.cpp", "ollama", "lm-studio"],
    license: "apache-2.0",
    sourceUrl: "https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct-GGUF",
    notes: "Incredibly small. Perfect for tiny machines, resource-constrained tasks, or fast testing."
  },
  {
    id: "meta-llama/Llama-3.2-1B-Instruct-GGUF",
    name: "Llama 3.2 1B Instruct",
    provider: "builtin",
    params: "1B",
    quantization: "Q4_K_M",
    sizeGb: 0.8,
    minimumRamGb: 4,
    recommendedRamGb: 8,
    runtimeTags: ["gguf", "llama.cpp", "ollama", "lm-studio"],
    license: "llama",
    sourceUrl: "https://huggingface.co/meta-llama/Llama-3.2-1B-Instruct-GGUF",
    notes: "Very lightweight. Good for basic experimentation and fast local runs."
  },
  {
    id: "Qwen/Qwen2.5-1.5B-Instruct-GGUF",
    name: "Qwen2.5 1.5B Instruct",
    provider: "builtin",
    params: "1.5B",
    quantization: "Q4_K_M",
    sizeGb: 1.1,
    minimumRamGb: 6,
    recommendedRamGb: 8,
    runtimeTags: ["gguf", "llama.cpp", "ollama", "lm-studio"],
    license: "apache-2.0",
    sourceUrl: "https://huggingface.co/Qwen/Qwen2.5-1.5B-Instruct-GGUF",
    notes: "Great lightweight agentic model with good balance of speed and logic capabilities."
  },
  {
    id: "google/gemma-2-2b-it-GGUF",
    name: "Gemma 2 2B IT",
    provider: "builtin",
    params: "2B",
    quantization: "Q4_K_M",
    sizeGb: 1.6,
    minimumRamGb: 6,
    recommendedRamGb: 8,
    runtimeTags: ["gguf", "llama.cpp", "ollama", "lm-studio"],
    license: "gemma",
    sourceUrl: "https://huggingface.co/google/gemma-2-2b-it-GGUF",
    notes: "Class-leading quality at the 2B size range."
  },
  {
    id: "meta-llama/Llama-3.2-3B-Instruct-GGUF",
    name: "Llama 3.2 3B Instruct",
    provider: "builtin",
    params: "3B",
    quantization: "Q4_K_M",
    sizeGb: 2.0,
    minimumRamGb: 6,
    recommendedRamGb: 8,
    runtimeTags: ["gguf", "llama.cpp", "ollama", "lm-studio"],
    license: "llama",
    sourceUrl: "https://huggingface.co/meta-llama/Llama-3.2-3B-Instruct-GGUF",
    notes: "Excellent small-size generalist model from Meta."
  },
  {
    id: "Qwen/Qwen2.5-3B-Instruct-GGUF",
    name: "Qwen2.5 3B Instruct",
    provider: "builtin",
    params: "3B",
    quantization: "Q4_K_M",
    sizeGb: 2.2,
    minimumRamGb: 6,
    recommendedRamGb: 8,
    runtimeTags: ["gguf", "llama.cpp", "ollama", "lm-studio"],
    license: "apache-2.0",
    sourceUrl: "https://huggingface.co/Qwen/Qwen2.5-3B-Instruct-GGUF",
    notes: "A solid small model for everyday prompting with modest hardware."
  },
  {
    id: "mistralai/Mistral-7B-Instruct-v0.3-GGUF",
    name: "Mistral 7B Instruct v0.3",
    provider: "builtin",
    params: "7B",
    quantization: "Q4_K_M",
    sizeGb: 4.4,
    minimumRamGb: 12,
    recommendedRamGb: 16,
    runtimeTags: ["gguf", "llama.cpp", "ollama", "lm-studio"],
    license: "apache-2.0",
    sourceUrl: "https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.3-GGUF",
    notes: "Strong general-purpose option for local use."
  },
  {
    id: "Qwen/Qwen2.5-7B-Instruct-GGUF",
    name: "Qwen2.5 7B Instruct",
    provider: "builtin",
    params: "7B",
    quantization: "Q4_K_M",
    sizeGb: 4.7,
    minimumRamGb: 12,
    recommendedRamGb: 16,
    runtimeTags: ["gguf", "llama.cpp", "ollama", "lm-studio"],
    license: "apache-2.0",
    sourceUrl: "https://huggingface.co/Qwen/Qwen2.5-7B-Instruct-GGUF",
    notes: "Good multilingual and coding-leaning option at the 7B size."
  },
  {
    id: "meta-llama/Llama-3.1-8B-Instruct-GGUF",
    name: "Llama 3.1 8B Instruct",
    provider: "builtin",
    params: "8B",
    quantization: "Q4_K_M",
    sizeGb: 4.9,
    minimumRamGb: 12,
    recommendedRamGb: 16,
    runtimeTags: ["gguf", "llama.cpp", "ollama", "lm-studio"],
    license: "llama",
    sourceUrl: "https://huggingface.co/meta-llama/Llama-3.1-8B-Instruct-GGUF",
    notes: "Popular balance of quality and local usability for many laptops and desktops."
  },
  {
    id: "google/gemma-2-9b-it-GGUF",
    name: "Gemma 2 9B IT",
    provider: "builtin",
    params: "9B",
    quantization: "Q4_K_M",
    sizeGb: 5.5,
    minimumRamGb: 12,
    recommendedRamGb: 16,
    runtimeTags: ["gguf", "llama.cpp", "ollama", "lm-studio"],
    license: "gemma",
    sourceUrl: "https://huggingface.co/google/gemma-2-9b-it-GGUF",
    notes: "Highly capable model with performance rivaling larger models."
  },
  {
    id: "meta-llama/Llama-3.1-14B-Instruct-GGUF",
    name: "Llama 3.1 14B Instruct",
    provider: "builtin",
    params: "14B",
    quantization: "Q4_K_M",
    sizeGb: 8.5,
    minimumRamGb: 24,
    recommendedRamGb: 32,
    runtimeTags: ["gguf", "llama.cpp", "ollama", "lm-studio"],
    license: "llama",
    sourceUrl: "https://huggingface.co/meta-llama/Llama-3.1-14B-Instruct-GGUF",
    notes: "Better quality, but more demanding. Best on higher-memory systems."
  }
];
